// import { Resend } from "resend";

// const resend = new Resend(process.env.RESEND_API_KEY);
// console.log(resend)

// export default async function handler(req: any, res: any) {
//   if (req.method !== "POST") {
//     return res.status(405).json({
//       error: "Method not allowed",
//     });
//   }

//   try {
//     const { to, subject, message } = req.body;

//     const data = await resend.emails.send({
//       from: "CareFinder <onboarding@resend.dev>",
//       to,
//       subject,
//       html: `
//         <h2>${subject}</h2>
//         <p>${message}</p>
//       `,
//     });

//     return res.status(200).json(data);
//   } catch (error) {
//     return res.status(500).json(error);
//   }
// }

import { Resend } from "resend";

export default async function handler(req: any, res: any) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const apiKey = process.env.RESEND_API_KEY;

    if (!apiKey) {
      return res.status(500).json({ error: "Missing API key" });
    }

    const resend = new Resend(apiKey);

    const { to, subject, hospitals } = req.body;

    const hospitalCards = hospitals
      .map(
        (h: any) => `
        <div style="
          border:1px solid #eee;
          border-radius:10px;
          padding:16px;
          margin-bottom:12px;
        ">
          <h3 style="margin:0; color:#5B65DC;">${h.name}</h3>
          <p style="margin:6px 0; color:#555;">
            📍 ${h.address || "No address provided"}
          </p>
          <p style="margin:6px 0; color:#555;">
            🏥 Specialty: ${h.specialty || "General"}
          </p>
          <p style="margin:6px 0; color:#555;">
            📞 ${h.phone || "N/A"}
          </p>
        </div>
      `
      )
      .join("");

    const html = `
      <div style="font-family:Arial;background:#f6f7fb;padding:40px 0;">
        <div style="max-width:600px;margin:auto;background:#fff;border-radius:12px;overflow:hidden;">

          <div style="background:#5B65DC;padding:20px;color:#fff;">
            <h2 style="margin:0;">Your Curated Hospital List</h2>
          </div>

          <div style="padding:20px;">
            <p style="color:#444;">
              Here are the hospitals you selected:
            </p>

            ${hospitalCards}

            <p style="font-size:12px;color:#888;margin-top:20px;">
              Generated by CareFinder
            </p>
          </div>

        </div>
      </div>
    `;

    const data = await resend.emails.send({
      from: "CareFinder <onboarding@resend.dev>",
      to,
      subject,
      html,
    });

    return res.status(200).json(data);
  } catch (error: any) {
    console.error(error);
    return res.status(500).json({ error: error.message });
  }
}